# Reusable workflow

name: base

# Controls when the action will run.
on:
  # Run only when called from another workflow
  workflow_call:
    secrets:
      REGISTRY_URL:
        required: true
      REGISTRY_USER:
        required: true
      REGISTRY_PASSWORD:
        required: true
      IMAGE_NAME:
        required: true

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-test:

    runs-on: ubuntu-latest
    container: node:14

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            ./*/node_modules
          key: v1-npm-deps-${{ hashFiles('**/yarn.lock') }}
          restore-keys: v1-npm-deps-

      - name: build
        run: |
          yarn
          yarn build
          yarn generate-components-api
          cd server && yarn
      - name: test
        run: yarn test

  docker:
    needs: build-and-test
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
      ACTIONS_STEP_DEBUG: true
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: build app
        run: |
          yarn
          yarn build
          yarn generate-components-api
          cd server && yarn

      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ secrets.REGISTRY_URL }}/${{ secrets.IMAGE_NAME }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=sha
