name: Auto Assign Issues to Projects

on:
  issues:
      types: [opened]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
jobs:
  assign_to_project:
    runs-on: ubuntu-latest
    name: Assign topic to Project
    steps:
    - name: Assign issues to GitHub Project
      uses: srggrs/assign-one-project-github-action@1.2.0
      with:
        project: 'https://github.com/epam/UUI/projects/1'
        column_name: 'Backlog'
