name: qa

# Controls when the action will run.
on:
    push:
        branches: [ qa ]
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  call-base-for-qa:
    # Call all jobs from base.yml
    uses: ./.github/workflows/base.yml
    secrets:
      REGISTRY_URL: ${{ secrets.REGISTRY_URL }}
      REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      COMMON_HELMCHART_NAME: ${{ secrets.COMMON_HELMCHART_NAME }}
      APP_NAME_BASE: ${{ secrets.APP_NAME_QA }}
    with:
      values-file: values.qa.yaml
      # TODO: After migrating prod environment we can use the same image name for prod and non-prod
      image-name: ui-nonprod
      # Common helmchart version may be the same for all nonprod envs (in this case the changes in helmchart will be applied to all nonprod envs after deploy)
      common-helmchart-ver: v3
