name: track_bundle_size
on:
    pull_request:
        branches:
            - main
            - develop

concurrency:
    group: ${{ github.workflow }}-${{ github.base_ref }}-${{ github.head_ref }}
    cancel-in-progress: true

jobs:
    track-bundle-size:
        runs-on: ubuntu-latest
        container: node:16
        # since this job is run in context of source repo (pull_request), then we should skip the workflow, because commenting won't work in case of forks.
        # the condition below checks that pull request is created from the same repo, not from a fork (https://github.com/orgs/community/discussions/26829).
        if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}
                  path: source-branch
            - uses: actions/setup-node@v1
              with:
                  node-version: '16.x'
            - uses: actions/cache@v2
              with:
                  path: |
                      node_modules
                      ./*/node_modules
                  key: v1-npm-deps-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: v1-npm-deps-
            - name: track-bundle-size-source
              working-directory: source-branch
              run: |
                  yarn
                  yarn track-bundle-size

            - name: Find Comment
              uses: peter-evans/find-comment@v2
              id: findPrevComment
              with:
                  issue-number: ${{ github.event.pull_request.number }}
                  comment-author: 'github-actions[bot]'
                  body-includes: 'Generated by: track-bundle-size'
            - name: Add comment
              uses: peter-evans/create-or-update-comment@v2
              with:
                  comment-id: ${{ steps.findPrevComment.outputs.comment-id }}
                  issue-number: ${{ github.event.pull_request.number }}
                  body-file: ./source-branch/.reports/trackBundleSize.md
                  edit-mode: replace
